version: '3'

services:
  migrations:
    &currency_base
    build:
      context: .
      dockerfile: ./migrations.dockerfile

    environment:
      db_host: postgres
      db_port: 5432
      db_user: postgres
      db_database: postgres
      db_password: postgres

    command: aerich upgrade

  bot:
    <<: *currency_base
    build:
      args:
        context: .
        dockerfile: ./Dockerfile

    command: python bot.py

  redis:
    image: redis
    volumes:
      - ./docker/redis/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
    # ports:
    #   - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 30s
      retries: 3

  postgres-bot:
    container_name: postgres-bot
    image: postgres:15-bullseye
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PG_USER: postgres

